# Generated by Django 4.2.3 on 2023-12-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_logs_log_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='log_time',
            new_name='time',
        ),
    ]
