# Generated by Django 4.2.3 on 2023-12-19 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_log_time_logs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
